server:
  port: 8080
  tomcat:
    #basedir: /logs
    accesslog:
      directory: was
      enabled: true
      file-date-format: .yyyy-MM-dd
      max-days: 30
      pattern: '%h %l %u %t "%r" %s %b %D'
      prefix: access
      rotate: true
      suffix: .log
  servlet:
    contextPath: /
    session:
      timeout: 14400

spring:
  config:
    useLegacyProcessing: true

# Swagger
springdoc:
  packages-to-scan: com.example.tfexample
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    # path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true